# Generated by Django 6.0 on 2025-12-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_interviewer_alter_job_salary_range_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='current_location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='work_preference',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('ONSITE', 'On-site'), ('HYBRID', 'Hybrid')], default='REMOTE', max_length=50),
        ),
    ]
