# Generated by Django 6.0 on 2025-12-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_candidate_current_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='match_score',
            field=models.FloatField(default=0.0),
        ),
    ]
